#### Imports

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, balanced_accuracy_score, f1_score

In [ ]:
# Importar os modelo



#### Functions

In [ ]:
def transform(dado, classe01 = "", classe02 = ""):
  lista = []
  for i in dado:
    if i == classe01:
      lista.append(0)
    else:
      lista.append(1)
    
  return np.array(lista)

#### Dataset

In [ ]:
df = pd.read_csv("/content/FIC.Full CSV.csv")

In [ ]:
df.head()

Age Age.Group  Gender Locality   Marital status                         \
0   45     41-50  Female      RURAL                               MARRIED   
1   51     51-60  Female      URBAN                               MARRIED   
2   55     51-60  Female      RURAL                               MARRIED   
3   55     51-60  Female      RURAL                               MARRIED   
4   56     51-60  Female      RURAL                               MARRIED   

  Life.Style                                                                                \
0                                                 NO                                         
1                                                 NO                                         
2                                                YES                                         
3                                                YES                                         
4                                                YES                                         

  Sleep Category Depression Hyperlipi  ... oldpeak slope  ca  thal num SK  \
0    NO     FREE        YES       YES  ...     3.0     2   0     7   2  1   
1    NO     FREE        YES       YES  ...     1.2     2   0     7   2  1   
2   YES     FREE        YES       YES  ...     3.4     2   0     3   2  1   
3   YES     FREE        YES       YES  ...     2.0     2   1     7   3  1   
4    NO     FREE        YES       YES  ...     4.0     3   2     7   3  1   

   SK.React  Reaction  Mortality  Follow.Up  
0        NO         0          0         60  
1        NO         0          0         15  
2        NO         0          0          6  
3        NO         0          0         52  
4        NO         0          0         34  

[5 rows x 60 columns]

In [ ]:
df.columns

Index(['Age', 'Age.Group', 'Gender', 'Locality  ',
       'Marital status                       ',
       'Life.Style                                                                              ',
       'Sleep', 'Category', 'Depression', 'Hyperlipi', 'Smoking',
       'Family.History', 'F.History', 'Diabetes', 'HTN', 'Allergies', 'BP',
       'Thrombolysis', 'BGR', 'B.Urea', 'S.Cr', 'S.Sodium', 'S.Potassium',
       'S.Chloride', 'C.P.K', 'CK.MB', 'ESR', 'WBC', 'RBC', 'Hemoglobin',
       'P.C.V', 'M.C.V', 'M.C.H', 'M.C.H.C', 'PLATELET_COUNT', 'NEUTROPHIL',
       'LYMPHO', 'MONOCYTE', 'EOSINO', 'Others ', 'CO', 'Diagnosis',
       'Hypersensitivity', 'cp', 'trestbps', 'chol', 'fbs', 'restecg',
       'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num', 'SK',
       'SK.React', 'Reaction', 'Mortality', 'Follow.Up'],
      dtype='object')

In [ ]:
df.Gender.unique()

array(['Female', 'Male'], dtype=object)

In [ ]:
df['Locality  '].unique(), df['Marital status                       '].unique()

(array(['RURAL', 'URBAN'], dtype=object),
 array(['MARRIED', 'SINGLE'], dtype=object))

In [ ]:
df.rename(columns = { 'Locality  ': 'Locality' }, inplace = True)

In [ ]:
df.rename(columns = { 'Marital status                       ': 'Marital_Status' }, inplace = True)

In [ ]:
df.Locality.unique()

array(['RURAL', 'URBAN'], dtype=object)

In [ ]:
df.Marital_Status.unique()

array(['MARRIED', 'SINGLE'], dtype=object)

#### Data Preprocessing

In [ ]:
gender = df.Gender
gender.shape

(368,)

In [ ]:
lista = [] # 0 se for female e 1 se for male

for i in gender:
  if i == "Female":
    lista.append(0)
  else:
    lista.append(1)

lista = np.array(lista)

In [ ]:
print(lista)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [ ]:
gender = lista

In [ ]:
gender.shape

(368,)

In [ ]:
locality = df.Locality

lista = [] # 0 se URBAN and 1 if RURAL

for i in locality:
  if i == 'URBAN':
    lista.append(0)
  else:
    lista.append(1)

locality = np.array(lista)

In [ ]:
print(locality)

[1 0 1 1 1 0 1 1 0 1 1 1 0 1 1 0 1 1 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0
 0 1 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1
 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1
 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 1
 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1 1 0 1 0 0 0 0 0 0 0
 0 1 0 0 0 0 1 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1
 1 1 0 1 1 1 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 1
 1 1 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 1]


In [ ]:
age = df.Age
print(age)

0      45
1      51
2      55
3      55
4      56
       ..
363    55
364    55
365    58
366    58
367    50
Name: Age, Length: 368, dtype: int64


In [ ]:
mortality = df.Mortality

In [ ]:
smoke = df.Smoking

In [ ]:
smoke.unique()

array(['NO', 'YES'], dtype=object)

In [ ]:
smoking = transform(smoke, "NO", "YES")

In [ ]:
married = df.Marital_Status
maried

0      MARRIED
1      MARRIED
2      MARRIED
3      MARRIED
4      MARRIED
        ...   
363    MARRIED
364    MARRIED
365    MARRIED
366    MARRIED
367    MARRIED
Name: Marital_Status, Length: 368, dtype: object

In [ ]:
married.unique()

array(['MARRIED', 'SINGLE'], dtype=object)

In [ ]:
marriedList = transform(maried, 'MARRIED', 'SINGLE')

In [ ]:
print(marriedList)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
# Criando um dataframe através das listas
data = {"age": age, "gender" : gender, "locality": locality, "smoking": smoking,
                    "mortality": mortality, "married" : marriedList}
df_new = pd.DataFrame(data)

In [ ]:
df_new.head()

age  gender  locality  smoking  mortality  married
0   45       0         1        0          0        0
1   51       0         0        0          0        0
2   55       0         1        0          0        0
3   55       0         1        0          0        0
4   56       0         1        0          0        0

In [ ]:
#### Criando o dataset para o treinamento

In [ ]:
X_data = df_new[["age", "gender", "locality", "smoking", "married"]].to_numpy()

In [ ]:
X_data

array([[45,  0,  1,  0,  0],
       [51,  0,  0,  0,  0],
       [55,  0,  1,  0,  0],
       ...,
       [58,  1,  0,  0,  0],
       [58,  1,  0,  1,  0],
       [50,  1,  1,  1,  0]])

In [ ]:
y_label = df_new.mortality.to_numpy()

In [ ]:
y_label

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,

In [ ]:
# Separando os dados com o train_test_split

x_train, x_test, y_train, y_test = train_test_split(X_data, y_label, train_size= 0.9)

In [ ]:
print(x_train.shape), print(y_train.shape)

(331, 5)
(331,)


(None, None)

#### Criando um Modelo de Classificação

In [ ]:
from sklearn.svm import SVC #importando o modelo

In [ ]:
#Criando o modelo
model_svc = SVC(kernel = 'rbf', degree = 4, C = 2.0)
# Treinando o modelo
model_svc.fit(x_train, y_train)

SVC(C=2.0, degree=4)

In [ ]:
predictSVC = model_svc.predict(x_test)
print(predictSVC)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
score = accuracy_score(y_test, predictSVC)
print("A acurácia medida pela accuracy_score é: {:.2f}%".format(score * 100))

A acurácia medida pela accuracy_score é: 72.97%


In [ ]:
score = balanced_accuracy_score(y_test, predictSVC)
print("A acurácia medida pela balanced_accuracy_score é: {:.2f}%".format(score * 100))

A acurácia medida pela balanced_accuracy_score é: 50.00%


In [ ]:
#### Classification Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
model_tree = DecisionTreeClassifier(criterion='gini')
model_tree.fit(x_train, y_train)

DecisionTreeClassifier()

In [ ]:
predictTree = model_tree.predict(x_test)

In [ ]:
predictTree

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
score = accuracy_score(y_test, predictTree)
print("A acurácia medida pela accuracy_score é: {:.2f}%".format(score * 100))

A acurácia medida pela accuracy_score é: 86.49%


In [ ]:
score = balanced_accuracy_score(y_test, predictTree)
print("A acurácia medida pela balanced_accuracy_score é: {:.2f}%".format(score * 100))

A acurácia medida pela balanced_accuracy_score é: 78.15%


In [ ]:
teste = np.array([[33, 1, 0, 1, 0]])
model_tree.predict(teste)

array([0])

In [ ]:
df_new.head()

age  gender  locality  smoking  mortality  married
0   45       0         1        0          0        0
1   51       0         0        0          0        0
2   55       0         1        0          0        0
3   55       0         1        0          0        0
4   56       0         1        0          0        0